// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/LEILEI0628/GoWeb/internal/repository"
	"github.com/LEILEI0628/GoWeb/internal/repository/cache"
	"github.com/LEILEI0628/GoWeb/internal/repository/dao"
	"github.com/LEILEI0628/GoWeb/internal/service"
	"github.com/LEILEI0628/GoWeb/internal/web"
	"github.com/LEILEI0628/GoWeb/internal/web/handler"
	"github.com/LEILEI0628/GoWeb/internal/web/router"
	"github.com/LEILEI0628/GoWeb/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddleware(cmdable)
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	redisCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, redisCache)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	userRouters := router.NewUserRouters(userHandler)
	routers := web.NewRouters(userRouters)
	engine := ioc.InitGin(v, routers)
	return engine
}
