# 设置整个服务栈的名称
name: goweb
services:
  mysql8:
    image: mysql:8.0
    restart: always
    command:
#      - 加入参数
      - --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 20010628
    volumes:
      #      设置初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      #      注意这里我映射为了 13306 端口
      - "13306:3306"
  redis:
    image: 'bitnami/redis:7.2'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '16379:6379'
  etcd:
    image: 'bitnami/etcd:3.5.9'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
#      使用 12379 端口来连接 etcd
      - "12379:2379"